{
 "title": "Overview",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "User pods running over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(phase) (kube_pod_status_phase{pod=~\"^jupyter-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Build pods running over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(phase) (kube_pod_status_phase{pod=~\"build-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker Image Pulls (in 5min interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(kubelet_runtime_operations_total{operation_type=\"pull_image\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful builds (in 5min intervals)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(node) (delta(binderhub_build_count_total{status=\"success\", repo!~\".*(jupyterlab-demo|ipython-in-depth|binder-examples).*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O on spko-css-app03",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{kubernetes_io_hostname=\"spko-css-app03\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "-sum(rate(container_network_transmit_bytes_total{kubernetes_io_hostname=\"spko-css-app03\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}