- name: Install generic depenencies
  hosts:
    - kubernetes_control_panel
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - python3-pip
          - python3-dev
