- name: Create Kubernetes Control Panel
  hosts:
    - kubernetes_control_panel
  become: true
  tasks:
    - name: Check if Kubernetes is running
      ansible.builtin.shell: >
        kubectl get nodes || /bin/true
      register: kubernetes_nodes
    - name: Pull kubernetes images
      when: kubernetes_nodes.stdout.find('control-plane') == -1
      ansible.builtin.shell: >
        kubeadm config images pull
        --cri-socket unix:///run/containerd/containerd.sock
    - name: Initialize the cluster
      when: kubernetes_nodes.stdout.find('control-plane') == -1
      ansible.builtin.shell: >
        kubeadm init
        --pod-network-cidr=10.244.0.0/16
        --upload-certs
        --control-plane-endpoint={{ K8S_CONTROL_PLANE_ENDPOINT }}
        --cri-socket unix:///run/containerd/containerd.sock
      register: kubeadm_init_output
    - name: Create root's .kube directory
      ansible.builtin.file:
        path: /root/.kube
        state: directory
        mode: 0755
    - name: Copies admin.conf to root's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: true
    - name: Create user's .kube directory
      ansible.builtin.file:
        path: /home/ansible/.kube
        state: directory
        mode: 0755
        owner: ansible
        group: ansible
    - name: Copies admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ansible/.kube/config
        remote_src: true
        owner: ansible
        group: ansible
    - name: Get the token for joining the worker nodes
      ansible.builtin.shell: >
        kubeadm token create --print-join-command
      register: kubernetes_join_command
    - name: Create temporary file
      ansible.builtin.file:
        path: /tmp/kubernetes_join_command
        state: touch
        owner: ansible
        group: ansible
    - name: Save content of join command
      ansible.builtin.copy:
        content: "{{ kubernetes_join_command.stdout }}"
        dest: /tmp/kubernetes_join_command
    - name: Copy join command to local file
      ansible.builtin.fetch:
        src: /tmp/kubernetes_join_command
        dest: '{{ ANSIBLE_CONTROL_NODE_TMP }}'
