- name: Install Kubernetes on Nodes
  hosts: all
  become: true
  tasks:
    - name: Download Kubernetes public GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
        dest: /tmp/kubernetes-archive-keyring.asc
        mode: '0644'
        force: true
    - name: Convert the public GPG key to binary
      ansible.builtin.command:
        argv:
          - gpg
          - --yes
          - --dearmor
          - --output
          - /tmp/kubernetes.gpg
          - /tmp/kubernetes-archive-keyring.asc
    - name: Copy GPG key
      ansible.builtin.copy:
        src: /tmp/kubernetes.gpg
        dest: /etc/apt/keyrings/kubernetes.gpg
        remote_src: true
        mode: '0644'
    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
        filename: kubernetes
        state: present
    - name: Add Helm public GPG key
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/trusted.gpg.d/helm.asc
        mode: '0644'
        force: true
    - name: Add Helm repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
        filename: kubernetes
        state: present
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        allow_downgrade: true
        pkg:
          - kubelet=1.32.*
          - kubeadm=1.32.*
          - kubectl=1.32.*
          - helm=3.16.*
