- name: Configure Kubernetes Node Affinity
  hosts:
    - kubernetes_control_panel
  tasks:
    - name: Add binderhub label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['binderhub'] %}
        kubectl label nodes {{ host }} binderhub=true
        {% else %}
        kubectl label nodes {{ host }} binderhub-
        {% endif %}
        {% endfor %}
    - name: Add docker_available label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['binderhub'] %}
        kubectl label nodes {{ host }} docker_available=true
        {% else %}
        kubectl label nodes {{ host }} docker_available-
        {% endif %}
        {% endfor %}
    - name: Add repo2docker label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['repo2docker'] %}
        kubectl label nodes {{ host }} repo2docker=true
        {% else %}
        kubectl label nodes {{ host }} repo2docker-
        {% endif %}
        {% endfor %}
    - name: Add component label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['repo2docker'] %}
        kubectl label nodes {{ host }} component=binderhub-build
        {% else %}
        kubectl label nodes {{ host }} component-
        {% endif %}
        {% endfor %}
    - name: Add database label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['notebooks_gesis_org'] %}
        kubectl label nodes {{ host }} database=postgresql
        {% else %}
        kubectl label nodes {{ host }} database-
        {% endif %}
        {% endfor %}
    - name: Add web server label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['notebooks_gesis_org'] %}
        kubectl label nodes {{ host }} web-server=nginx
        {% else %}
        kubectl label nodes {{ host }} web-server-
        {% endif %}
        {% endfor %}
