- name: Install Container Network Interface (CNI) Flannel
  hosts:
    - kubernetes_control_panel
  tasks:
    - name: Remove Flannel
      kubernetes.core.k8s:
        state: absent
        src: https://github.com/coreos/flannel/raw/master/Documentation/kube-flannel.yml
    - name: Install Tigera Calico operator
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/projectcalico/calico/v3.26.3/manifests/tigera-operator.yaml
    - name: Install Calico and resource
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', '../calico/custom-resources.yaml') | from_yaml_all }}"
