- name: Install Kubernetes on Nodes
  hosts: all
  become: true
  tasks:
    - name: Remove old Kubernetes public GPG key
      ansible.builtin.file:
        path: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
        state: absent
    - name: Add Kubernetes public GPG key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.27/deb/Release.key
        dest: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.asc
        mode: '0644'
        force: true
    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.27/deb/ /"
        filename: kubernetes
        state: present
    - name: Add Helm public GPG key
      ansible.builtin.get_url:
        url: https://baltocdn.com/helm/signing.asc
        dest: /etc/apt/trusted.gpg.d/helm.asc
        mode: '0644'
        force: true
    - name: Add Helm repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm.asc] https://baltocdn.com/helm/stable/debian/ all main"
        filename: kubernetes
        state: present
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - kubelet=1.28.*
          - kubeadm=1.28.*
          - kubectl=1.28.*
          - helm=3.12.*
