- name: Create Kubernetes Cluster
  hosts:
    - kubernetes_control_panel
  become: true
  tasks:
    - name: Pull kubernetes images
      ansible.builtin.shell: >
        kubeadm config images pull
        --cri-socket unix:///run/containerd/containerd.sock
    - name: Initialize the cluster
      ansible.builtin.shell: >
        kubeadm init
        --pod-network-cidr=10.244.0.0/16
        --upload-certs
        --control-plane-endpoint={{ K8S_CONTROL_PLANE_ENDPOINT }}
        --cri-socket unix:///run/containerd/containerd.sock
