- name: Prepare Kubernetes Nodes
  hosts: all
  become: true
  tasks:
    - name: Ensure DOCKER_CLIENT_TIMEOUT is set
      ansible.builtin.lineinfile:
        path: /etc/environment
        regexp: '^DOCKER_CLIENT_TIMEOUT='
        line: DOCKER_CLIENT_TIMEOUT=180
    - name: Disable SWAP since kubernetes can't work with swap enabled
      ansible.builtin.shell: swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    - name: Disable Firewall
      ansible.builtin.shell: ufw disable
    - name: Allow IP forward
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
    - ansible.posix.sysctl:
        name: fs.inotify.max_user_instances
        value: '1280'
        state: present
    - ansible.posix.sysctl:
        name: fs.inotify.max_user_watches
        value: '655360'
        state: present
    - name: Create /orc2_data/containerd directory if it does not exist
      ansible.builtin.file:
        path: /orc2_data/containerd
        state: directory
    - name: Create /orc2_data/repo2docker directory if it does not exist
      ansible.builtin.file:
        path: /orc2_data/repo2docker
        state: directory
    - name: Create /orc2_data/prometheus directory if it does not exist
      ansible.builtin.file:
        path: /orc2_data/prometheus
        state: directory
    - name: Create /orc2_data/grafana directory if it does not exist
      ansible.builtin.file:
        path: /orc2_data/grafana
        state: directory
    - name: Create /orc2_data/alertmanager directory if it does not exist
      ansible.builtin.file:
        path: /orc2_data/alertmanager
        state: directory
