- name: Install GitLab agent for Kubernetes
  hosts:
    - kubernetes_control_panel
  tasks:
    - name: Add repository
      kubernetes.core.helm_repository:
        name: gitlab
        repo_url: https://charts.gitlab.io
    - name: Deploy GitLab agent
      kubernetes.core.helm:
        name: gitlab-agent
        chart_ref: gitlab/gitlab-agent
        release_namespace: gitlab-agent
        dependency_update: true
        create_namespace: true
        set_values:
          - value: 'config.token={{ GITLAB_K8S_TOKEN }}'
          - value: config.kasAddress=wss://git.gesis.org/-/kubernetes-agent/
