- name: Configure Kubernetes Node Affinity
  hosts:
    - kubernetes_control_panel
  tasks:
    - name: Add harbor label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['harbor'] %}
        kubectl label nodes {{ host }} harbor=true
        {% else %}
        kubectl label nodes {{ host }} harbor-
        {% endif %}
        {% endfor %}
    - name: Add hub.jupyter.org/node-purpose label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['binderhub'] %}
        kubectl label nodes {{ host }} hub.jupyter.org/node-purpose=core
        {% else %}
        kubectl label nodes {{ host }} hub.jupyter.org/node-purpose-
        {% endif %}
        {% endfor %}
    - name: Add binderhub label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['binderhub'] %}
        kubectl label nodes {{ host }} binderhub=true
        kubectl label nodes {{ host }} hub.jupyter.org/node-purpose=core
        {% else %}
        kubectl label nodes {{ host }} binderhub-
        kubectl label nodes {{ host }} hub.jupyter.org/node-purpose-
        {% endif %}
        {% endfor %}
    - name: Add docker_available label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['binderhub'] %}
        kubectl label nodes {{ host }} docker_available=true
        {% else %}
        kubectl label nodes {{ host }} docker_available-
        {% endif %}
        {% endfor %}
    - name: Add database label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['notebooks_gesis_org'] %}
        kubectl label nodes {{ host }} database=postgresql
        {% else %}
        kubectl label nodes {{ host }} database-
        {% endif %}
        {% endfor %}
    - name: Add web server label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['notebooks_gesis_org'] %}
        kubectl label nodes {{ host }} web-server=nginx
        {% else %}
        kubectl label nodes {{ host }} web-server-
        {% endif %}
        {% endfor %}
    - name: Add prometheus label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['prometheus'] %}
        kubectl label nodes {{ host }} prometheus=true
        {% else %}
        kubectl label nodes {{ host }} prometheus-
        {% endif %}
        {% endfor %}
    - name: Add grafana label
      ansible.builtin.shell: |
        {% for host in hostvars %}
        {% if host in groups['grafana'] %}
        kubectl label nodes {{ host }} grafana=true
        {% else %}
        kubectl label nodes {{ host }} grafana-
        {% endif %}
        {% endfor %}
