- name: Prepare Kubernetes Nodes
  hosts:
    - kubernetes_control_panel
    - jupyterhub
    - jupyterhub_single_user
  become: true
  tasks:
    - name: Disable swap
      ansible.builtin.shell: swapoff -a
    - name: Disable Firewall
      ansible.builtin.shell: ufw disable
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
    - name: Allow IP forward
      copy:
        dest: /proc/sys/net/ipv4/ip_forward
        content: |
          1
