- name: Install web server
  hosts:
    - notebooks_gesis_org
  become: true
  tasks:
    - name: Install nginx
      ansible.builtin.apt:
        allow_change_held_packages: true
        pkg:
          - nginx=1.18.*
          - python3-passlib
