- name: Prepare node
  hosts: all
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - rsync
          - python3-pip
          - python3-dev
          - apt-transport-https
          - ca-certificates
          - curl
