- name: Prepare node
  hosts:
    - kubernetes_control_panel
    - notebooks_gesis_org
    - binderhub
    - jupyterhub_single_user
  become: true
  tasks:
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - rsync
          - python3-pip
          - python3-dev
          - apt-transport-https
          - ca-certificates
          - curl
