apiVersion: v1
kind: Service
metadata:
  name: harbor-ingress-nginx-nodeport
  namespace: {{.Release.Namespace}}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: binderhub-harbor-ingress
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
