apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-jobservice
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      harbor: jobservice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-registry
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      harbor: registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-redis
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      harbor: redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-trivy
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      harbor: trivy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: harbor-database
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  selector:
    matchLabels:
      harbor: database
