apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: gesis
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gesis
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: gesis
  rules:
    - host: {{ .Values.url_domain }}
      http:
        paths:
          - path: /grafana/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-grafana
                port:
                  number: 80
          - path: /prometheus/
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-prometheus
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: binder
                port:
                  number: 80
