apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 1.0.0-0.dev.git.3548.h83da55db
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 26.0.1
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.8.2
- condition: cryptnono.enabled
  name: cryptnono
  repository: https://cryptnono.github.io/cryptnono/
  version: 0.3.1-0.dev.git.153.h8956dbb
- name: harbor
  repository: https://helm.goharbor.io
  version: 1.15.1
description: GESIS BinderHub
name: gesis
type: application
version: 3.0.0
