apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 1.0.0-0.dev.git.3332.h7baa4b8
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.1.0
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.60.4
- condition: cryptnono.enabled
  name: cryptnono
  repository: https://yuvipanda.github.io/cryptnono/
  version: 0.2.1
description: GESIS BinderHub
name: gesis
type: application
version: 3.0.0
