apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 1.0.0-0.dev.git.3373.h41b9d77
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.10.0
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 7.2.4
- condition: cryptnono.enabled
  name: cryptnono
  repository: https://cryptnono.github.io/cryptnono/
  version: 0.3.1-0.dev.git.129.ha9d73b8
description: GESIS BinderHub
name: gesis
type: application
version: 3.0.0
