apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: binderhub
  repository: https://jupyterhub.github.io/helm-chart
  version: 1.0.0-0.dev.git.3506.hba24eb2a
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 25.27.0
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 8.5.6
- condition: cryptnono.enabled
  name: cryptnono
  repository: https://cryptnono.github.io/cryptnono/
  version: 0.3.1-0.dev.git.143.hfc89744
- name: harbor
  repository: https://helm.goharbor.io
  version: 1.15.1
description: GESIS BinderHub
name: gesis
type: application
version: 3.0.0
