---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minesweeper
rules:
# needs read/exec/logs/delete access
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minesweeper
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: minesweeper
roleRef:
  kind: Role
  name: minesweeper
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minesweeper
