mybinder.org sync bot script lint:
  stage: test
  rules:
    - if: (($CI_PIPELINE_SOURCE != "schedule") && $CI_COMMIT_BRANCH == 'main') || $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - bot/mybinder.org/bot.py
  image: 
    name: docker-private-snapshots.gesis.intra/gesis/ilcm/orc2/test:latest
  dependencies: []
  script:
    - black --check bot/mybinder.org/

mybinder.org sync bot execution:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $GITLAB_CI_SCHEDULE_NAME == 'sync-mybinder.org'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes:
        - bot/mybinder.org/bot.py
  image: 
    name: docker-private-snapshots.gesis.intra/gesis/ilcm/orc2/test:latest
  dependencies: []
  script:
    - python bot/mybinder.org/bot.py
