- name: Configure Kubernetes
  hosts: kubernetes_control_panel
  become: true
  tasks:
    - name: Disable swap
      ansible.builtin.shell: swapoff -a
    - name: Disable Firewall
      ansible.builtin.shell: ufw disable
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
    - name: Install dependencies
      ansible.builtin.apt:
        update_cache: true
        pkg:
          - kubelet
          - kubeadm
          - kubectl
