- ansible.builtin.import_playbook: plays/k8s-prepare-node.yml
- ansible.builtin.import_playbook: plays/k8s-install.yml
- ansible.builtin.import_playbook: plays/nginx-install.yml
- ansible.builtin.import_playbook: plays/nginx-config.yml
