- name: Update NGINX configuration
  hosts: notebooks_gesis_org
  become: true
  tasks:
    - name: Copy static files
      ansible.builtin.copy:
        src: nginx/static/
        dest: /var/www/
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Copy configuration files
      ansible.builtin.copy:
        src: nginx/sites-available/
        dest: /etc/nginx/sites-available/
        owner: root
        group: root
        mode: u=rw,g=r,o=r
