- name: Update NGINX configuration
  hosts: notebooks_gesis_org
  tasks:
    - name: Copy static files
      ansible.builtin.copy:
        src: nginx/static/
        dest: /var/www/
      become: true
