- name: Update NGINX configuration
  hosts: notebooks_gesis_org
  become: true
  tasks:
    - name: Copy static files
      ansible.builtin.copy:
        src: ../nginx/static/
        dest: /var/www/orc2
        owner: nginx
        group: nginx
        mode: u=rw,g=r,o=r
    - name: Copy configuration files
      ansible.builtin.copy:
        src: ../nginx/sites-available/
        dest: /etc/nginx/sites-available/
        owner: nginx
        group: nginx
        mode: u=rw,g=r,o=r
    - name: Create HTTP Basic Authentication
      community.general.htpasswd:
        path: /etc/nginx/passwdfile
        name: gesis
        password: {{ PROMETHEUS_PASSWORD }}
        owner: nginx
        group: nginx
        mode: u=rw,g=r
    - name: Create a symbolic link
      ansible.builtin.file:
        src: /etc/nginx/sites-available/orc2
        dest: /etc/nginx/sites-enabled/orc2
        state: link
    - name: Reload server
      ansible.builtin.systemd:
        state: reloaded
        name: nginx

- name: Create storage point for Kubernetes
  hosts: notebooks_gesis_org
  become: true
  tasks:
    - name: Create root directory
      ansible.builtin.file:
        path: /orc2_data
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Create directory for prometheus
      ansible.builtin.file:
        path: /orc2_data/prometheus
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Create directory for grafana
      ansible.builtin.file:
        path: /orc2_data/grafana
        state: directory
        mode: u=rwx,g=rx,o=rx
    - name: Create directory for alert
      ansible.builtin.file:
        path: /orc2_data/alertmanager
        state: directory
        mode: u=rwx,g=rx,o=rx
