- ansible.builtin.import_playbook: plays/install-generic-dependencies.yml
- ansible.builtin.import_playbook: plays/k8s-prepare-node.yml
- ansible.builtin.import_playbook: plays/k8s-install.yml
- ansible.builtin.import_playbook: plays/k8s-bridge-traffic.yml
- ansible.builtin.import_playbook: plays/k8s-install-containerd.yml
- ansible.builtin.import_playbook: plays/k8s-create-control-panel.yml
- ansible.builtin.import_playbook: plays/k8s-install-cni.yml
- ansible.builtin.import_playbook: plays/k8s-create-generic-worker-nodes.yml
- ansible.builtin.import_playbook: plays/k8s-create-jupyterhub-worker-nodes.yml
- ansible.builtin.import_playbook: plays/k8s-node-affinity.yml
- ansible.builtin.import_playbook: plays/k8s-install-gitlab-agent.yml
- ansible.builtin.import_playbook: plays/cron4k8s.yml
- ansible.builtin.import_playbook: plays/nginx-install.yml
- ansible.builtin.import_playbook: plays/nginx-config.yml
