# Use https://github.com/jupyterhub/mybinder.org-deploy/blob/main/config/prod.yaml as reference

url: https://notebooks.gesis.org/binder/

binderhub:
  config:
    BinderHub:
      hub_url: https://notebooks.gesis.org/binder/jupyter/
      image_prefix: gesiscss/binder-r2d-g5b5b759-

  extraConfig:
    02-badge-base-url: |
      c.BinderHub.badge_base_url = "https://mybinder.org/"

prometheus:
  enabled: true
  server:
    livenessProbeInitialDelay: 800
    resources:
      requests:
        cpu: "4"
        memory: 30Gi
      limits:
        cpu: "4"
        memory: 36Gi
    persistentVolume:
      size: 50Gi
      storageClass: standard
    retention: 30d
    ingress:
      hosts:
        - prometheus.notebooks.gesis.org

grafana:
  enabled: true
  resources:
    requests:
      cpu: "0"
      memory: 128Mi
    limits:
      cpu: "0.25"
      memory: 128Mi
  ingress:
    hosts:
      - grafana.notebooks.gesis.org
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.notebooks.gesis.org
          isDefault: true
          editable: false
  persistence:
    storageClassName: standard

cryptnono:
  enabled: true

nfs:
  enabled: true
  nfs:
    server: 194.95.75.12
    path: /ssd
