url: https://notebooks.gesis.org/binder/

binderhub:
  config:
    BinderHub:
      hub_url: https://notebooks.gesis.org/binder/jupyter/
      image_prefix: gesiscss/binder-r2d-g5b5b759-

prometheus:
  enabled: true
  server:
    livenessProbeInitialDelay: 800
    resources:
      requests:
        cpu: "4"
        memory: 30Gi
      limits:
        cpu: "4"
        memory: 36Gi
    persistentVolume:
      size: 50Gi
    retention: 30d
    ingress:
      hosts:
        - prometheus.notebooks.gesis.org

grafana:
  enabled: true

cryptnono:
  enabled: true

nfs:
  enabled: true
  nfs:
    server: 194.95.75.12
    path: /sdd
