project:
  type: book


book:
  title: "Open Research Computing (ORC)"
  author:
    - Raniere Silva
  chapters:
    - index.qmd
    - where-to-ask-questions.qmd
    - part: "Explanation"
      chapters:
      - what-is.qmd
    - part: "Tutorial: Set your Development Environment"
      chapters: 
      - development-environment.qmd
      - hello-minikube.qmd
      - local-jupyterhub.qmd
      - local-binderhub.qmd
    - part: "Tutorial: Set the Test Environment"
      chapters:
      - test-hardware.qmd
      - test-software.qmd
      - test-k8s-cluster.qmd
      - test-k8s-setup.qmd
      - test-postgresql.qmd
      - test-binderhub.qmd
      - test-nginx.qmd
      - test-clean-up.qmd
    - part: "Tutorial: Set the Production Environment"
      chapters: 
      - production-hardware.qmd
      - production-software.qmd
      - production-storage.qmd
      - production-gitlab-ci-runner.qmd
      - production-ansible.qmd
      - production-k8s-cluster.qmd
      - production-k8s-setup.qmd
      - production-k8s-storage.qmd
      - production-binderhub.qmd
      - production-nginx.qmd
      - production-monitoring-status.qmd
    - part: "How-to Guides: Password"
      chapters: 
      - how-to/share-password-and-tokens.qmd
      - how-to/share-password-database.qmd
      - how-to/share-secret-files.qmd
    - part: "How-to Guides: Git"
      chapters: 
      - how-to/git-repositories.qmd
      - how-to/git-crypt-install.qmd
      - how-to/git-crypt.qmd
      - how-to/personal-access-tokens.qmd
      - how-to/gitlab-install-agent.qmd
      - how-to/inspect-running-single-user-pod.qmd
      - how-to/dev-binderhub.qmd
    - part: openlens/index.qmd
      chapters: 
        - openlens/install.qmd
        - openlens/connect.qmd
    - part: "How-to Guides: Bots"
      chapters: 
        - bots/is-fix-jupyterhub-running.qmd
        - bots/get-log-fix-jupyterhub.qmd
        - bots/is-kill-succeeded-pods-running.qmd
        - bots/get-log-kill-succeeded-pods.qmd
    - part: "How-to Guides: Site Reliability"
      chapters: 
        - sre/docker-in-docker.qmd
    - part: "Explanation"
      chapters: 
      - explanation/orc2-fix-jupyterhub.qmd
      - explanation/kill-succeeded-pods.qmd
    - part: "Reference"
      chapters: 
      - gitlab-ci-runner-101.qmd
      - docker-101.qmd
      - nginx-101.qmd
      - postgresql-101.qmd
      - helm-101.qmd
  appendices:
    - version-log-book.qmd

format:
  html:
    theme: cosmo
