project:
  type: book


book:
  title: "Open Research Computing (ORC)"
  author:
    - Raniere Silva
  chapters:
    - index.qmd
    - part: "General"
      chapters: 
      - where-to-ask-questions.qmd
    - part: "Production Environment"
      chapters: 
      - production-hardware.qmd
      - production-software.qmd
      - production-k8s-cluster.qmd
      - production-k8s-setup.qmd
      - production-nginx.qmd
  appendices:
    - version-log-book.qmd
    - git-crypt.qmd
    - nginx-101.qmd
    - postgresql-101.qmd
    - openlens-101.qmd
    - helm-101.qmd
    - dev-binderhub.qmd

format:
  html:
    theme: cosmo