project:
  type: book


book:
  title: "Open Research Computing (ORC)"
  author:
    - Raniere Silva
  chapters:
    - index.qmd
    - part: "General"
      chapters: 
      - where-to-ask-questions.qmd
      - secret-files.qmd
      - git-repositories.qmd
      - personal-access-tokens.qmd
    - part: "Development Environment"
      chapters: 
      - development-environment.qmd
      - hello-minikube.qmd
      - local-jupyterhub.qmd
      - local-binderhub.qmd
    - part: "Test Environment"
      chapters:
      - test-hardware.qmd
      - test-software.qmd
      - test-k8s-cluster.qmd
      - test-k8s-setup.qmd
      - test-postgresql.qmd
      - test-binderhub.qmd
      - test-nginx.qmd
      - test-clean-up.qmd
    - part: "Production Environment"
      chapters: 
      - production-hardware.qmd
      - production-software.qmd
      - production-k8s-cluster.qmd
      - production-k8s-setup.qmd
      - production-binderhub.qmd
      - production-nginx.qmd
    - part: "Continuous Deployment"
      chapters: 
      - gitlab-install-agent.qmd
  appendices:
    - version-log-book.qmd
    - git-crypt.qmd
    - nginx-101.qmd
    - postgresql-101.qmd
    - openlens-101.qmd
    - helm-101.qmd
    - dev-binderhub.qmd

format:
  html:
    theme: cosmo