name: status-verification
run-name: ${{ github.actor }} is checking GESIS Notebook
on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-22.04
    env:
      SECRET_GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install pytest requests
      - run: pytest --binder-url https://notebooks.gesis.org/binder/ --hub-url https://notebooks.gesis.org/binder/jupyter/ test
