# Use https://github.com/jupyterhub/mybinder.org-deploy/blob/main/config/prod.yaml as reference

url: https://notebooks.gesis.org/binder/

binderhub:
  config:
    BinderHub:
      hub_url: https://notebooks.gesis.org/binder/jupyter/

    LaunchQuota:
      total_quota: 250

  extraConfig:
    02-badge-base-url: |
      c.BinderHub.badge_base_url = "https://mybinder.org/"
    01-template-variables: |
      template_vars = {
        "gesis_notebooks_https": 'https://notebooks.gesis.org/',
        'production': True,
      }
      template_vars['gesis_notebooks_static'] = template_vars['gesis_notebooks_https'] + "static/"
      template_vars['gesis_web_frontend_framework'] = template_vars['gesis_notebooks_static'] + "gesis-web-frontend-framework/"
      template_vars['binder_static'] = template_vars['gesis_notebooks_https'] + "binder/static/"
      c.BinderHub.template_variables.update(template_vars)

prometheus:
  enabled: true
  server:
    service:
      type: NodePort
      nodePort: 30073
      servicePort: 80
    livenessProbeInitialDelay: 800
    resources:
      requests:
        cpu: "4"
        memory: 30Gi
      limits:
        cpu: "4"
        memory: 36Gi
    persistentVolume:
      size: 50Gi
      storageClass: standard
    retention: 30d
    ingress:
      hosts:
        - notebooks.gesis.org/prometheus

grafana:
  enabled: true
  resources:
    requests:
      cpu: "0"
      memory: 128Mi
    limits:
      cpu: "0.25"
      memory: 128Mi
  ingress:
    path: /grafana
    hosts:
      - notebooks.gesis.org

  # Configure Grafana datasources
  # ref: http://docs.grafana.org/administration/provisioning/#datasources
  datasources:
    datasources.yaml:
      apiVersion: 1
      prune: true
      deleteDatasources:
        - name: mybinder.org
          orgId: 1
        - name: notebooks.gesis.org
          orgId: 1
        - name: prometheus
          orgId: 1
      datasources:
        - name: GESIS Notebooks Prometheus
          orgId: 1
          type: prometheus
          # We use the Kubernetes Cluster Networking
          # ref: https://kubernetes.io/docs/concepts/cluster-administration/networking/
          url: http://binderhub-prometheus-server
          isDefault: true
          editable: false

  persistence:
    storageClassName: standard

cryptnono:
  enabled: true
